name: CI for docker-multi
on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build client image
        run: docker build -t ayule/react-test -f ./client/Dockerfile.dev ./client

      - name: Test client image
        run: docker run -e CI=true ayule/react-test npm test
